import pandas as pd
city_names = pd.Series(['San Francisco', 'San Jose', 'Sacramento'])
population = pd.Series([852469, 1015785, 485199])
cities = pd.DataFrame({ 'City name': city_names, 'Population': population })
print('----------column-----------------')
print (type(cities['City name']))
print('----------column City name-----------------')
print(cities['City name'])
print('----------column Population-----------------')
print(cities['Population'])
print('----------value: Line and Column-----------------')
print (type(cities['City name'][1]))
print(cities['City name'][1])
print('----------DataFrame:Table-----------------')
print (type(cities[0:2]))
print(cities[0:2])
print('---------cities[0:1]------------------')
print(cities[0:1])
print('---------cities------------------')
print(cities)
print('---------cities.head------------------')
print(cities.head(2))
print('----------population / 1000-----------------')
print(population / 1000)